# Generated by Django 3.2.5 on 2022-05-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('input', models.TextField()),
                ('input_translation', models.TextField(blank=True)),
                ('protein_sequence', models.TextField(blank=True)),
                ('protein_product', models.TextField(blank=True)),
                ('protein_id', models.TextField(blank=True)),
                ('position', models.IntegerField(default=-1)),
                ('job_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
